name: greentrition
description: Intolerance nutrition.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+105

environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+4
  http: 0.13.1
  html: 0.15.0
  google_fonts: ^2.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  share_plus: ^6.3.0

  html_unescape: ^2.0.0
  shimmer: ^2.0.0
  fluttertoast: ^7.1.6
  show_more_text_popup:
    git:
      url: https://github.com/Juphex/flutter_show_popup.git
  icon_shadow: ^1.0.1
  photo_view: ^0.13.0
  pie_chart: ^5.1.0
#  syncfusion_flutter_charts: ^19.4.50

  google_sign_in: ^5.0.1
  sign_in_with_apple: ^3.0.0

  graphql: ^4.0.1

  path_provider: ^2.0.1

  in_app_purchase: ^3.0.8

  google_mobile_ads: ^0.12.1
  firebase_analytics: ^10.0.6
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  #firebase_ml_vision:
  #  git:
  #    url: git://github.com/algirdasmac/flutterfire
  #    path: packages/firebase_ml_vision

  #see https://pub.dev/packages/google_ml_kit
  google_ml_kit: ^0.9.0
  cloud_firestore: ^4.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/nutrition/original/
    - assets/icons/nutrition/compressed/
    - assets/images/
    - assets/platform/

  fonts:
    - family: Helsinki
      fonts:
        - asset: fonts/Helsinki.ttf

    - family: Recoleta
      fonts:
        - asset: fonts/Recoleta-bold.ttf

    - family: QuincyCf
      fonts:
        - asset: fonts/FontsFree-Net-quincy-cf-bold.ttf

    - family: Nimbus
      fonts:
        - asset: fonts/NimbusSanL-Bol.otf

    - family: SilkSerif
      fonts:
        - asset: fonts/SilkSerif-Medium.ttf

    - family: Untitled
      fonts:
        - asset: fonts/UNTITLED.TTF

    - family: SilkSerifReg
      fonts:
        - asset: fonts/SilkSerif-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true